### ISSUE TITLE
Is Rack::Utils::DEFAULT_SEP the split character?

### ISSUE THREAD

**Issue by tokland** [brianhempel/hash_to_hidden_fields#3]
Not sure this is correct:

```
pairs = cleaned_hash.to_query.split(Rack::Utils::DEFAULT_SEP)
```

Checking the source code of ```Hash#to_query```, it always uses "&" as separator,  not that constant.

**Comment by vemv** [comment]
```ruby
pry(main)> Rack::Utils::DEFAULT_SEP
=> /[&;] */n
```
This regex looks quite more complete than the string '&', surely it handles some corner cases?

**Comment by vemv** [comment]
> Checking the source code of Hash#to_query, it always uses "&" as separator, not that constant.
We could apply the robustness principle here... :) https://en.wikipedia.org/wiki/Robustness_principle

**Comment by brianhempel** [comment]
Interesting.

I'm going to close this issue unless there's actually a known bug here.
